# Generated by Django 4.2.6 on 2023-10-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_multiplephoto_task_alter_multiplephoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplephoto',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
