# Generated by Django 4.2.6 on 2023-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_photo_multiplephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplephoto',
            name='task',
        ),
        migrations.AlterField(
            model_name='multiplephoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/'),
        ),
    ]
